### ISSUE TITLE
long long integers are not properly supported.

### ISSUE THREAD

**Issue by tbitcs** [MaJerle/lwjson#12]
long long integers are not correctly supported due to how prv_parse_number is using lwjson_real_t for parsing integers. Even if lwjson_real_t is defined as a double, this only allows storing up to 53 bit integers (assuming you are using a system which supports IEEE 754 double precision floating point numbers). I propose adding a second variable handle the value as an integer. I will follow up with a pull request.

**Comment by MaJerle** [comment]
Thanks - I agree - I added a comment in the pull-request.
