### ISSUE TITLE
Could you please provide a example code print out a string value? and int value?

### ISSUE THREAD

**Issue by 9to1url** [MaJerle/lwjson#18]
I have this code but print out more than the value, it keeps print out all the string after that:

```
                /* Find custom key in JSON */
                if ((t = lwjson_find(&lwjson, "session")) != NULL) {
                    printf("Key found with data type: %d\r\n", (int)t->type);
                    size_t tokenValueLen = lwjson_get_val_string_length(t);
                    const char* sessionID = lwjson_get_val_string(t, tokenValueLen);
                    printf("session id: %s\r\n", sessionID);
                }
```
it prints:
session id: 01J6Z7PK7QE6XFJ27DCQW7QZ7M","msgtyp":"Receiver.Online",

**Comment by MaJerle** [comment]
`printf("session id: %.*s\r\n", (int)tokenValueLen, sessionID);` should do the job I guess.

To prevent copying JSON to memory, strings are not NULL terminated. Instead, length is provided to user.

**Comment by 9to1url** [comment]
Great works now. Your lib is great for carefully memory consideration. Very good for embedded devices.
Please add above in your document to increase user adoption. thanks
